In [1]:
import tensorflow as tf
import numpy as np


In [2]:
mat_1 = [[10,20,30],
         [40,50,60]]

In [3]:
mat_2 = tf.constant([[10,20,30],[40,50,60]])

In [4]:
mat_3 = np.array([[10,20,30],[40,50,60]])

In [5]:
print(mat_1)

[[10, 20, 30], [40, 50, 60]]


In [6]:
print(mat_2)

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [7]:
print(mat_3)

[[10 20 30]
 [40 50 60]]


In [8]:
h=tf.constant("Hello ")
t=tf.constant("Tensorflow!")
ht = h+t
print(ht)

tf.Tensor(b'Hello Tensorflow!', shape=(), dtype=string)


# import tensorflow as tf

## Without session in tensorflow

In [12]:
a=tf.constant([1,2,3])
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [13]:
s=tf.compat.v1.Session()
print(s.run(a))

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().